import random as r

hangman_words = {
    "lemon": "HINT: It's a citrus, but not the sweetest.",
    "elephant": "HINT: Known for its memory and size.",
    "guitar": "HINT: Often played with a pick or fingers.",
    "python": "HINT: It slithers or codes, depending on context.",
    "mountain": "HINT: A peak that stands tall.",
    "ocean": "HINT: Deep, vast, and often blue.",
    "diamond": "HINT: A girl's best friend, they say.",
    "sunflower": "HINT: Tall and yellow, it faces the light.",
    "umbrella": "HINT: Handy in unexpected showers.",
    "chocolate": "HINT: A sweet temptation, dark or milk.",
    "castle": "HINT: A fortress fit for royalty.",
    "rocket": "HINT: It shoots for the stars.",
    "kangaroo": "HINT: Famous jumper from Down Under.",
    "sapphire": "HINT: A gem as blue as the sky.",
    "piano": "HINT: The keys to melody and harmony.",
    "penguin": "HINT: A tuxedoed bird that can't fly.",
    "cactus": "HINT: Thrives in the arid and spiny.",
    "island": "HINT: Surrounded entirely by blue.",
    "lantern": "HINT: Lights the way in the dark.",
    "compass": "HINT: Always points you in the right direction.",
    "rainbow": "HINT: Seven hues that follow the rain.",
    "volcano": "HINT: Dormant or active, it erupts.",
    "octopus": "HINT: Eight limbs and underwater wisdom.",
    "galaxy": "HINT: Where stars and planets reside.",
    "labyrinth": "HINT: A maze with twists and turns.",
    "anchor": "HINT: Keeps a vessel grounded at sea.",
}
